config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :messages do
    get 'sent', on: :collection
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessor :to
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
  default_scope -> { order('created_at DESC') }
  before_validation :set_receiver_id
  validates :sender_id, presence: true, numericality: { only_integer: true }
  validates :receiver_id, presence: true, numericality: { only_integer: true }
  validates :content, presence: true, length: { maximum: 1000 }

  private
    def set_receiver_id
      if receiver_id.nil?
        receiver = User.find_by(username: to)
        self.receiver_id = receiver.id unless receiver.nil?
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user
  before_action :set_message, only: [:show, :destroy]
  before_action :correct_user, only: [:show, :destroy]

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = 'Message sent!'
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def index
    @messages = current_user.received_messages.paginate(page: params[:page])
  end

  def show
  end

  def sent
    @messages = current_user.messages.paginate(page: params[:page])
  end

  def destroy
    @message.destroy
    flash[:success] = "Message deleted!"
    redirect_to messages_path
  end

  private
    def message_params
      params.require(:message).permit(:content, :to, :receiver_id)
    end

    def set_message
      @message = Message.find(params[:id])
    end

    def correct_user
      @message =  Message.find(params[:id])
      redirect_to(root_url) unless current_user?(@message.sender) || current_user?(@message.receiver)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<li>
  <% if current_page?(messages_path) %>
    <%= render 'user_info', object: message.sender %>
  <% else %>
    <%= render 'user_info', object: message.receiver %>
  <% end %>
  | <%= link_to "view", message_path(message) %>
  | <%= link_to "delete", message, method: :delete, data: { confirm: "You sure?" } %>
  <span class="content"><%= message.content %></span>
  <span class="timestamp">
    Sent <%= time_ago_in_words(message.created_at) %> ago.
  </span>
</li>

app/views/messages/_messages.html.erb
<div class="col-md-8">
  <% if @messages.any? %>
    <ul class="messages">
      <%= render @messages %>
    </ul>
    <%= will_paginate %>
  <% end %>
</div>

app/views/messages/_sidebar.html.erb
<aside class="col-md-4">
  <ul>
    <li><%= link_to "New Message", new_message_path %></li>
    <li><%= link_to "Inbox", messages_path %></li>
    <li><%= link_to "Sent Messages", sent_messages_path %></li> 
  </ul>
</aside>

app/views/messages/_user_info.html.erb
<%= gravatar_for object, size: 52 %>
<%= link_to object.name, object %>

app/views/messages/index.html.erb
<% provide(:title, "Inbox") %>
<h1>Messages</h1>
<div class="row">
  <%= render 'sidebar' %>
  <%= render 'messages' %>
</div>

app/views/messages/new.html.erb
<% provide(:title, "New Message") %>
<h1>New Message</h1>
<div class="row">
  <%= render 'sidebar' %>
  <div class="col-md-8">
    <%= form_for(@message) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :to %>
      <%= f.text_field :to, class: "form-control" %>

      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>

      <%= f.button "Send", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/messages/sent.html.erb
<% provide(:title, "Sent Messages") %>
<h1>Sent Messages</h1>
<div class="row">
  <%= render 'sidebar' %>
  <%= render 'messages' %>
</div>

app/views/messages/show.html.erb
<%= provide(:title, "View Message") %>
<h1>View Message</h1>
<div class="row">
  <%= render 'sidebar' %>
  <div class="col-md-8">
    <div class="jumbotron">
      <h3>To: <%= link_to @message.receiver.name, @message.receiver %></h3>
      <h3>From: <%= link_to @message.sender.name, @message.sender %></h3>
      <span class="timestamp">
        Sent <%= time_ago_in_words(@message.created_at) %> ago.
      </span>
    </div>
    <span><%= @message.content %></span>
  </div>
</div>