config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :messages do
    get 'sent', on: :collection
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if object.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: object %>
  </ol>
  <%= will_paginate object %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <% if !current_page?(user_path(feed_item.user)) %>
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
  <% end %>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <%= render 'shared/micropost_delete', object: feed_item %>
</li>

app/views/shared/_home_non_signed_in.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), "http://rubyonrails.org/" %>

app/views/shared/_home_signed_in.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="span8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/shared/_home_user_profile.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed', object: @feed_items %>
  </div>
</div>

app/views/shared/_home_welcome.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <p>
    This is the home page for the
    <a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
    sample application.
  </p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), "http://rubyonrails.org/" %>

app/views/shared/_micropost_delete.html.erb
<% if current_user?(object.user) %>
  <%= link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.content %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "Compose new micropost..." %>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <%= f.button "Post", class: "btn btn-lg btn-primary" %>
    </div>
    <div class="col-sm-1">
      <span class="word-countdown">140</span>
    </div>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user, size: 52), @user %>
<h1>
  <%= @user.name %>
</h1>
<span><%= link_to "@#{@user.username}", @user, class: "text-muted" %></span>
<% if !current_page?(user_path(@user)) %>
  <span>
    <%= pluralize(@user.microposts.count, "micropost") %>
  </span>
<% end %>